pasantias/urls.py
from django.urls import path 
from . import views 

app_name = 'pasantias' 
urlpatterns = [
    path('', views.index, name='index'),
    
    path('coordinador/', views.coordinador, name= "coordinador"),
    path('estudiante/', views.estudiante, name= "estudiante"),

    #login
    path('ingresar/', views.form_Ing, name='form_Ing'),
    path('Ing_post/', views.post_Ing, name="post_Ing"),
    
    #logout
    path('logout/', views.view_logout, name='view_logout'),

    #registro
    path('registro/', views.form_Reg, name='form_Reg'),
    path('Reg_post/', views.post_Reg, name="post_Reg"),

    #crea convenio
    path('convenio_post/', views.post_crea_convenio, name="post_crea_convenio"),

    #crea solicitud
    path('solicitud_post/', views.post_crea_solicitud, name="post_crea_solicitud"),

    #cambiar estado
    path('c_estado_post/', views.post_cambia_solicitud, name='post_cambia_solicitud')

 
]

pasantiasweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('pasantias/', include('pasantias.urls')),
    path('admin/', admin.site.urls),
]

pasantias/models.py
from django.db import models
from django.contrib.auth.models import User



class Empresa(models.Model):
    nombre = models.CharField(max_length=200, null=True)
    facultad = models.CharField(max_length=200, null=True)


class Solicitud(models.Model):
    estado = models.CharField(max_length=10, null=True)

    usuario = models.ForeignKey(
        User,
        related_name='solicitudes',
        on_delete=models.PROTECT
    )
    empresa = models.ForeignKey(
        Empresa,
        related_name='solicitudes',
        on_delete=models.PROTECT
    )
    def __str__(self):
        return self.estado

    class Meta:
        app_label = 'pasantias'

pasantias/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from pasantias.models import Empresa, Solicitud
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


#pagina anonimo 

def index(request):
    #Obtiene las empresas
    lista_empresas = Empresa.objects.all()
    #Crea el contexto
    contexto = {
        'lista_empresas': lista_empresas
       
    }
    #Envia el contexto al template
    return render(request, 'pasantias/index.html', contexto)


#pagina coordinador

@login_required
def coordinador(request):
    #Obtiene las empresas y solicitudes
    lista_solicitudes = Solicitud.objects.all()
    lista_empresas = Empresa.objects.all()        
    #Crea el contexto
    contexto = {
        'lista_solicitudes': lista_solicitudes,
        'lista_empresas': lista_empresas
    }
    
    return render(request, 'pasantias/Coordinador.html', contexto)


#pagina estudiante

@login_required
def estudiante(request):
    #Obtiene las empresas
    lista_empresas = Empresa.objects.all()
    lista_solicitudes = Solicitud.objects.all()
    #Crea el contexto
    contexto = {
        'lista_solicitudes': lista_solicitudes,
        'lista_empresas': lista_empresas
        
    }
    #Envia el contexto al template
    return render(request, 'pasantias/Estudiante.html', contexto)


#Registro

def form_Reg(request):
    return render(request, 'pasantias/form_Reg.html')

def post_Reg(request):
    #obtiene la informacion del formulario
    username = request.POST['username']
    nombres = request.POST['first_name']
    apellidos = request.POST['last_name']
    email = request.POST['email']
    password = request.POST['password']
    tipo = bool(request.POST['is_superuser'])

    #Crea el objeto
    usuario = User()
    usuario.username = username
    usuario.first_name = nombres
    usuario.last_name = apellidos
    usuario.email = email
    usuario.set_password(password)
    usuario.is_superuser = tipo 

    #guarda el objeto en la BD
    usuario.save()

    return redirect('pasantias:form_Ing')
    

#Login
    
def form_Ing(request):
    return render(request, 'pasantias/form_Ing.html')

def post_Ing(request):
    #obtiene la información del formulario
    u = request.POST['username']
    p = request.POST['password']
    tipo = bool(request.POST['is_superuser'])

    #Obtiene el usuario con los datos digitados
    usuario = authenticate(username=u, password=p)

    if usuario is not None:

        if tipo == True and usuario.is_superuser:

            login(request, usuario)
            return redirect('pasantias:coordinador')
                
        elif tipo == True and not usuario.is_superuser:

            return redirect('pasantias:form_Ing')
                
        elif tipo == False and usuario.is_superuser:

            return redirect('pasantias:form_Ing')
            
        elif tipo == False and not usuario.is_superuser:

            login(request, usuario)
            return redirect('pasantias:estudiante')
           
        else:
            return redirect('pasantias:form_Ing')
    else:
        return redirect('pasantias:form_Ing')
        #return render(request, 'pasantias/form_Ing')
        

#Logout

def view_logout(request):
    logout(request)
 
  # Redirecciona la página de login
    return redirect('pasantias:form_Ing')


#Crear convenio

def post_crea_convenio(request):
    n = request.POST['nombre']
    f = request.POST['facultad']

    empresa = Empresa(nombre=n, facultad=f)
    empresa.save()

    return redirect('pasantias:coordinador')


#Solicitar pasantia

def post_crea_solicitud(request):
    emp_id = request.POST['empresa_id']
    usu_id = request.user.id

    solicitud = Solicitud(empresa_id=emp_id, usuario_id=usu_id)
    solicitud.save()
    
    return redirect('pasantias:estudiante')


#Cambiar estado de solictud

def post_cambia_solicitud(request):
    estado = request.POST['cambio']
    id_solicitud = int(request.POST['id_c'])

    solicitud = Solicitud.objects.get(id=id_solicitud)
    solicitud.estado=estado
    solicitud.save()        
    
    return redirect('pasantias:coordinador')

pasantias/templates/pasantias/Coordinador.html
{% extends "pasantias/base.html" %} {% load static %} {% block titulo %}Coor
Pasantías{% endblock %} {% block estilo %}<link
  rel="stylesheet"
  href="{% static 'pasantias/css/estiloCoor.css' %}"
/>{% endblock %} {% block contenido %}
<nav class="navi">
  <ul>
    <li class="nav-item active">
      <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    </li>
    <li>
      <button type="button" class="btn btn-secondary">
        <a href="{% url 'pasantias:view_logout' %}">Salir</a>
      </button>
    </li>
  </ul>
</nav>
<section>
  <h3>
    Crear Convenio
  </h3>
  <br />
  <div>
    <form action="{% url 'pasantias:post_crea_convenio' %}" method="post">
      {% csrf_token %}
      <span>Ingrese la Facultad:</span>
      <input
        type="text"
        name="facultad"
        placeholder="Escriba la facultad"
        size="50"
      />
      <br /><br />
      <span>Ingrese el nombre de la empresa:</span>
      <input
        type="text"
        name="nombre"
        placeholder="Escriba la empresa"
        size="50"
      />
      <br /><br />
      <input type="submit" value="Enviar" />
    </form>
  </div>

  <br /><br />
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Empresa</th>
        <th scope="col">Facultad</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_empresas %}
            <li class="list-group-item">{{ c.nombre }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_empresas %}
            <li class="list-group-item">{{ c.facultad }}</li>
            {% endfor %}
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</section>
<section>
  <h3>
    Lista de solicitudes
  </h3>
  <br />
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Estudiante</th>
        <th scope="col">Codigo</th>
        <th scope="col">Correo</th>
        <th scope="col">Empresa</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %}
            <li class="list-group-item">{{ c.id }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %}
            <li class="list-group-item">
              {{ c.usuario.first_name }} {{ c.usuario.last_name }}
            </li>
            {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %}
            <li class="list-group-item">{{ c.usuario.username }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %}
            <li class="list-group-item">{{ c.usuario.email }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %}
            <li class="list-group-item">{{ c.empresa.nombre }}</li>
            {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %}
            <li class="list-group-item">
              {{ c.estado }}
            </li>
            {% endfor %}
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
  <h4>Cambiar estado de solicitud</h4>
  <form action="{% url 'pasantias:post_cambia_solicitud' %}" method="post">
    {% csrf_token %}
    <span>Ingrese el ID de la solicitud: </span>
    <input type="number" placeholder="ID" size="20px" name="id_c" />
    <br /><br />
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01">Estado</label>
      </div>
      <select class="custom-select" id="inputGroupSelect01" name="cambio">
        <option selected value="None"
          >Seleccione el estado de la solicitud</option
        >
        <option value="Aceptado">Aceptado</option>
        <option value="Rechazado">Rechazado</option>
        <option value="En proceso">En proceso</option>
      </select>
    </div>
    <br />
    <button type="submit">Cambiar</button>
  </form>
</section>
<footer>
  <p>Universidad Santo Tomás derechos reservados.</p>
</footer>
{% endblock %}

pasantias/templates/pasantias/Estudiante.html
{% extends "pasantias/base.html" %} {% load static %} {% block titulo %}Est
Pasantías{% endblock %} {% block estilo %}<link
  rel="stylesheet"
  href="{% static 'pasantias/css/estiloEst.css' %}"
/>{% endblock %} {% block contenido %}
<nav class="navi">
  <ul>
    <li class="nav-item">
      <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    </li>
    <li>
      <button type="button" class="btn btn-secondary">
        <a href="{% url 'pasantias:view_logout' %}">Salir</a>
      </button>
    </li>
  </ul>
</nav>
<section>
  <article class="artic2">
    <h3>
      Empresas Disponibles para hacer tu pasantía
    </h3>
    <br />
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Empresa</th>
          <th scope="col">Facultad</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <ul class="list-group list-group-flush">
              {% for c in lista_empresas %}
              <li class="list-group-item">{{ c.nombre }}</li>
              {% endfor %}
            </ul>
          </td>
          <td>
            <ul class="list-group list-group-flush">
              {% for c in lista_empresas %}
              <li class="list-group-item">{{ c.facultad }}</li>
              {% endfor %}
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </article>
</section>
<section>
  <h3>Solicitar Pasantía</h3>
  <br />
  <form action="{% url 'pasantias:post_crea_solicitud' %}" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01"
          >Seleccione la Empresa</label
        >
      </div>
      <select class="custom-select" id="inputGroupSelect01" name="empresa_id">
        <option selected>Choose...</option>
        {% for c in lista_empresas %}
        <option value="{{ c.id }}">{{ c.nombre }}</option>
        {% endfor %}
      </select>
    </div>
    <br />
    <input type="submit" value="Enviar" />
  </form>
</section>
<section>
  <h3>Tu solicitud:</h3>
  <br />
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Empresa</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %} 
            {% if request.user.id == c.usuario_id %}
            <li class="list-group-item">{{ c.empresa.nombre }}</li>
            {% endif %} {% endfor %}
          </ul>
        </td>
        <td>
          <ul class="list-group list-group-flush">
            {% for c in lista_solicitudes %} 
            {% if request.user.id == c.usuario_id %}
            <li class="list-group-item">{{ c.estado }}</li>
            {% endif %} {% endfor %}
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</section>
<footer>
  <p>Universidad Santo Tomás derechos reservados.</p>
</footer>
{% endblock %}

pasantias/templates/pasantias/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block titulo %}{% endblock %}</title>
    {% block estilo %}{% endblock %}
    <meta name="author" content="Sergio Andres Castiblanco Rodríguez" />
    <meta
      name="description"
      content="Pagina de pasantías de la universidad santo tomás"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <header class="cabecera">
      <img src="{% static 'pasantias/img/usta2.png' %}" alt="" />
    </header>
    {% block contenido %} {% endblock %}
  </body>
</html>

pasantias/templates/pasantias/form_Ing.html
{% extends "pasantias/base.html" %} {% load static %} {% block titulo %}Ingresar
P{% endblock %} {% block estilo %}<link
  rel="stylesheet"
  href="{% static 'pasantias/css/estiloIng.css' %}"
/>{% endblock %} {% block contenido %}
<nav class="navi">
  <ul>
    <li>
      <button type="button" class="btn btn-secondary">
        <a href="{% url 'pasantias:index' %}">Volver</a>
      </button>
    </li>
  </ul>
</nav>
<section
  class="shadow-lg p-3 mb-5 bg-white rounded"
  class="p-3 mb-2 bg-light text-dark"
>
  <form action="{% url 'pasantias:post_Ing' %}" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01"
          >Tipo de usuario</label
        >
      </div>
      <select class="custom-select" id="inputGroupSelect01" name="is_superuser">
        <option value="">Estudiante</option>
        <option value="1">Administrador</option>
      </select>
    </div>
    <br />
    <br />
    <div>
      <label>Codigo:</label>
      <input type="text" name="username" />
      <br /><br />
      <label>Contraseña:</label>
      <input type="password" name="password" />
      <br /><br />
      <input type="submit" value="Enviar" />
    </div>
  </form>
</section>
<footer>
  <p>Universidad Santo Tomás derechos reservados.</p>
</footer>
{% endblock %}

pasantias/templates/pasantias/form_Reg.html
{% extends "pasantias/base.html" %} {% load static %} {% block titulo %}Registro
P{% endblock %} {% block estilo %}<link
  rel="stylesheet"
  href="{% static 'pasantias/css/estiloReg.css' %}"
/>{% endblock %} {% block contenido %}
<nav class="navi">
  <ul>
    <li>
      <button type="button" class="btn btn-secondary">
        <a href="{% url 'pasantias:index' %}">Volver</a>
      </button>
    </li>
  </ul>
</nav>
<section
  class="shadow-lg p-3 mb-5 bg-white rounded"
  class="p-3 mb-2 bg-light text-dark"
>
  <form action="{% url 'pasantias:post_Reg' %}" method="post">
    {% csrf_token %}
    <h5>Seleccione el tipo de usuario</h5>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <label class="btn btn-secondary">
        <input type="radio" name="is_superuser" value="" checked /> Estudiante
      </label>
      <label class="btn btn-secondary">
        <input type="radio" name="is_superuser" value="1" /> Administrador
      </label>
    </div>
    <br /><br />
    <span>Nombre:</span>
    <input
      type="text"
      name="first_name"
      placeholder="Escriba su nombre"
      size="50"
    />
    <br /><br />
    <span>Apellido:</span>
    <input
      type="text"
      name="last_name"
      placeholder="Escriba su apellido"
      size="50"
    />
    <br /><br />
    <span>Correo Institucional:</span>
    <input type="text" name="email" placeholder="Escriba su correo" size="50" />
    <br /><br />
    <label>Codigo:</label>
    <input type="text" name="username" />
    <br /><br />
    <label>Contraseña:</label>
    <input type="password" name="password" />
    <br /><br />
    <input type="submit" value="Submit" />
  </form>
</section>
<footer>
  <p>Universidad Santo Tomás derechos reservados.</p>
</footer>
{% endblock %}

pasantias/templates/pasantias/index.html
{% extends "pasantias/base.html" %}
{% load static %}
{% block titulo %}Usta Pasantias{% endblock %}    
{% block estilo %}<link rel="stylesheet" href="{% static 'pasantias/css/estilo.css' %}">{% endblock %}
{% block contenido %}
<nav class="navi" >
  <ul>
      <li>
        <button type="button" class="btn btn-secondary">
          <a href="{% url 'pasantias:form_Ing' %}" >Ingresar</a>
        </button>
      </li>
      <li>
        <button type="button" class="btn btn-secondary">
          <a href="{% url 'pasantias:form_Reg' %}">Registrarse</a>
        </button>
      </li>
  </ul>
</nav>
<div>
<section>
  <article >
      <h3>Cómo solicitar tu pasantía</h1>
            <p>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Pariatur dolores assumenda quos. Totam illo, commodi consequatur eligendi esse aliquam quasi cum saepe voluptatibus veritatis quaerat nisi at similique qui dolor culpa eius cumque dolorem voluptates molestiae pariatur consectetur explicabo. Fuga eligendi consequuntur, totam autem rerum voluptatibus numquam repudiandae aperiam maxime obcaecati, quae, eum cupiditate deleniti quidem accusamus quam labore nulla!
              </p>
      <ol>
          <li>paso</li>
          <li>paso</li>
          <li>paso</li>
          <li>paso</li>
      </ol>
  </article>
</section>
<br>
<section>
  <article class="artic2">
      <h3>
          Empresas Disponibles para hacer tu pasantía
      </h3>
      <br>
      <table class="table">
        <thead class="thead-dark">
            <tr>
              <th scope="col">Empresa</th>
              <th scope="col">Facultad</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <ul class="list-group list-group-flush">
                  {% for c in lista_empresas  %}
                  <li class="list-group-item">{{ c.nombre }}</li>
                  {% endfor %}
                </ul>
              </td>
              <td>
                <ul class="list-group list-group-flush">
                  {% for c in lista_empresas  %}
                  <li class="list-group-item">{{ c.facultad }}</li>
                  {% endfor %}
                  </ul>
              </td>
            </tr> 
          </tbody>
        </table>
  </article>
</section>
</div>

<footer>
  <p>Universidad Santo Tomás derechos reservados.</p>
</footer>
{% endblock %}
       